### ISSUE TITLE
License

### ISSUE THREAD

**Issue by auton1** [awohns/ldgm#35]
Thank you for releasing this code. I'm very much looking forward to trying it out! However... before I do so, could you please clarify what license the code is released under?

Thank you!

**Comment by awohns** [comment]
Thanks for your interest in LDGMs!
We’re planning to add an MIT license to the code. 
Please let us know if you need any help/guidance running the code, as well as any comments/suggestions you have.

**Comment by aauton** [comment]
Thank you!
